version: '3.4'
services:
  deploy_test:
    image: "${REGISTRY_NAME}devclubiitd/deploy_test:0.1"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: "unless-stopped"
    build: .
    env_file:
      - ./.env
    ports:
      - '${PORT}'
    environment:
      - VIRTUAL_HOST
    networks:
      - "internal"
      - "reverseproxy"

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
